# Generated by Django 5.0.1 on 2024-01-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
